In [5]:
import pandas as pd

In [6]:
list = [[1,2,3],[4,5,6]]

df_list = pd.DataFrame(list, columns=['col1','col2','col3'])
df_list

col1  col2  col3
0     1     2     3
1     4     5     6

In [8]:
import numpy as np

In [9]:
array = np.array(list)
df_arr = df_list = pd.DataFrame(array, columns = ['col1','col2','col3'])
df_arr

col1  col2  col3
0     1     2     3
1     4     5     6

In [10]:
dict = {'col1' : [1,11], 'col2' : [2,22], 'col3' : [3,33]}
df_dict = pd.DataFrame(dict)
df_dict

col1  col2  col3
0     1     2     3
1    11    22    33

In [11]:
dict = {'col1' : [1,11], 'col2' : [2,22], 'col3' : [3,33]}
df_dict = pd.DataFrame(dict, index = ['one', 'two'])
df_dict

col1  col2  col3
one     1     2     3
two    11    22    33

In [50]:
data = {'Name' : ['Chulmin', 'EunKyung', 'Jinwoong', 'Soobeom'], 'Year' : [2011, 2016, 2015, 2015], 'Gender' : ['Male', 'Female', 'Male', 'Male']}
data_df = pd.DataFrame(data, index = ['one', 'two', 'three', 'Four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    EunKyung  2016  Female
three  Jinwoong  2015    Male
Four    Soobeom  2015    Male

In [13]:
array = df_dict.values
print('df_dict.values 타입 : ', type(array))
print('df_dict.values shape : ', array.shape)
print(array)

df_dict.values 타입 :  <class 'numpy.ndarray'>
df_dict.values shape :  (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [14]:
list = df_dict.values.tolist()
print('df_dict.values.tolist() 타입 : ', type(list))
print(list)

df_dict.values.tolist() 타입 :  <class 'list'>
[[1, 2, 3], [11, 22, 33]]


In [15]:
dict = df_dict.to_dict('list')
print('df_dict.to_dict() 타입 : ', type(dict))
print(dict)

df_dict.to_dict() 타입 :  <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [27]:
pd.DataFrame['Gender']

TypeError: 'type' object is not subscriptable

In [28]:
data_df['Gender']

one        Male
two      Female
three      Male
Four       Male
Name: Gender, dtype: object

In [29]:
data_df[['Gender']]

Gender
one      Male
two    Female
three    Male
Four     Male

In [32]:
data_df[['name', 'Gender']]

name  Gender
one     Chulmin    Male
two    EunKyung  Female
three  Jinwoong    Male
Four    Soobeom    Male

In [34]:
data_df[1:3]

name  Year  Gender
two    EunKyung  2016  Female
three  Jinwoong  2015    Male

In [35]:
data_df2 = data_df.copy()
data_df2

name  Year  Gender
one     Chulmin  2011    Male
two    EunKyung  2016  Female
three  Jinwoong  2015    Male
Four    Soobeom  2015    Male

In [81]:
data_df_reset = data_df.reset_index(drop=True)
data_df_reset

Name  Year  Gender
0   Chulmin  2011    Male
1  EunKyung  2016  Female
2  Jinwoong  2015    Male
3   Soobeom  2015    Male

In [40]:
data_df_reset = data_df_reset.rename(columns={'index' : 'old_index'})
data_df_reset.index = data_df_reset.index + 1
data_df_reset

old_index      name  Year  Gender
1       one   Chulmin  2011    Male
2       two  EunKyung  2016  Female
3     three  Jinwoong  2015    Male
4      Four   Soobeom  2015    Male

In [41]:
data_df2.set_index('Year', inplace=True)
data_df2

name  Gender
Year                  
2011   Chulmin    Male
2016  EunKyung  Female
2015  Jinwoong    Male
2015   Soobeom    Male

In [43]:
array1 = np.arange(start =1, stop=10)
print(array1)
array2 = array1[array1 > 5]
print(array2)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [44]:
data_df[data_df['Year'] > 2012]

name  Year  Gender
two    EunKyung  2016  Female
three  Jinwoong  2015    Male
Four    Soobeom  2015    Male

In [52]:
data_df[data_df['Year'] > 2012][['Name', 'Gender']]

Name  Gender
two    EunKyung  Female
three  Jinwoong    Male
Four    Soobeom    Male

In [58]:
data_df[(data_df['Year'] > 2012) & (data_df['Gender'] == 'Male')][['Name']]

Name
three  Jinwoong
Four    Soobeom

In [59]:
data_df.iloc[1,0]

'EunKyung'

In [60]:
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [73]:
data_df.iloc[[1, 2], :]

Name  Year  Gender
two    EunKyung  2016  Female
three  Jinwoong  2015    Male

In [74]:
data_df.iloc[[0, 2], [0, 1]]

Name  Year
one     Chulmin  2011
three  Jinwoong  2015

In [75]:
data_df.loc['one', 'Name']

'Chulmin'

In [86]:
data_df_reset.loc[1:2]

Name  Year  Gender
1  EunKyung  2016  Female
2  Jinwoong  2015    Male

In [133]:
titanic_df = pd.read_csv('../data/titanic_train.csv', encoding = 'utf-8')
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [106]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500  C000        S

In [91]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [96]:
titanic_df_drop = titanic_df.dropna()
titanic_df_drop.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [97]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [131]:
titanic_df[titanic_df['Age'].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [120]:
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('N')

In [121]:
titanic_df_groupby = titanic_df.groupby(by = 'Pclass')
type(titanic_df_groupby)

pandas.core.groupby.generic.DataFrameGroupBy

In [126]:
titanic_df[['Age', 'Fare']].mean()

Fare    32.204208
dtype: float64

In [127]:
titanic_df_groupby = titanic_df.groupby(by = 'Pclass').count()
titanic_df_groupby.head()

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  216    216    216     216   216   
2               184       184   184  184  184    184    184     184   184   
3               491       491   491  491  491    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         216       216  
2         184       184  
3         491       491

In [128]:
titanic_df_groupby = titanic_df.groupby(by = 'Pclass')[['PassengerId', 'Survived']].count()
titanic_df_groupby.head()

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [135]:
titanic_df_groupby = titanic_df.groupby(by = 'Pclass')[['Age']].agg([min, max])
titanic_df_groupby

Age      
         min   max
Pclass            
1       0.92  80.0
2       0.67  70.0
3       0.42  74.0

In [136]:
agg_format = {'Age' : 'max', 'SibSp' : 'sum', 'Fare' : 'mean'}
titanic_df.groupby(by = 'Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [137]:
pd.pivot_table(titanic_df, index=['Pclass'])

Age       Fare     Parch  PassengerId     SibSp  Survived
Pclass                                                                 
1       38.233441  84.154687  0.356481   461.597222  0.416667  0.629630
2       29.877630  20.662183  0.380435   445.956522  0.402174  0.472826
3       25.140620  13.675550  0.393075   439.154786  0.615071  0.242363

In [138]:
pd.pivot_table(titanic_df, index=['Pclass', 'Sex'], values='Fare', aggfunc=np.sum)

Fare
Pclass Sex              
1      female  9975.8250
       male    8201.5875
2      female  1669.7292
       male    2132.1125
3      female  2321.1086
       male    4393.5865

In [139]:
def get_square(a):
    return a**2
print('3의 제곱은 : ', get_square(3))

3의 제곱은 :  9


In [142]:
titanic_df['Age_Cat'] = titanic_df['Age'].apply(lambda x : 
                                               'Child' if x <= 15
                                               else 'Adult' if x <= 60
                                               else 'Eldery')
titanic_df['Age_Cat'].value_counts()

Adult     609
Eldery    199
Child      83
Name: Age_Cat, dtype: int64